### ISSUE TITLE
Toasted-marshmallow for performance boost.

### ISSUE THREAD

**Issue by burdettadam** [openwallet-foundation/acapy#2349]
While looking into some performance testing we noticed serialize and deserialize are often called. Marshmallow could be a bottleneck. We should consider using https://github.com/lyft/toasted-marshmallow for a significant performance boost.

**Comment by ff137** [comment]
I notice that `toasted-marshmallow` is last updated 4 years ago ... maybe I'm wrong, but I would be skeptical to use that instead of base `marshmallow`, which seems fairly well maintained by comparison

I don't know the repos, so I asked GPT4 to look at the readme's and explain

toasted marshmallow would yield a performance boost in theory because:
> it implements a Just-In-Time (JIT) compiler for marshmallow. JIT is a technique where a computer program compiles into native code or bytecode at runtime, rather than prior to execution. This has the advantage of better runtime performance, as the compiler has more information about the program's state.

However, there's the caveat:
> Remember, though, that for toastedmarshmallow to be effective, it's critical that you re-use Schema objects. If you're creating a new Schema object every time you serialize/deserialize an object, you'll likely have worse performance.

So, is that the actual cause of why the code is slow? Creating of new Schema objects every time it's called? 
I'm not sure what to make of that, maybe someone else can pick up on that given that idk how the schema serialisation/deserialisation is happening in the codebase!

Note that performance bottlenecks can also be due to the size of data being processed ... a solution would be remove unnecessary data before de/serialisation. Also, json.dumps is called a lot ... like, a lot - 449 results if I search for it. Which, afaik is not the best choice for large data / high performance ... It's late, someone else take it from here 😄

**Comment by swcurran** [comment]
So even though Toasted Marshmallow has a totally cool name, it sounds like it is a no go.  Agreed?

@andrewwhitehead — highlighting this to add you to the conversation.
