### ISSUE TITLE
Question API: Send Presentation without pres_ex_id or with connection_id

### ISSUE THREAD

**Issue by ikamii** [openwallet-foundation/acapy#3321]
Hi there, 

I am using aca-py for my master's thesis and trying to achieve the trust between user and my system. 

What I am trying to achieve is to expose the system's VC to the user's wallet so they can be sure that they have connected with the right entity.

Is there a way to send VC presentation without needing a request first?

Thanks in advance!

**Comment by swcurran** [comment]
Hi @ikamii -- we discussed this briefly at the ACA-Pug meeting ([recording here](https://zoom.us/rec/share/a3PCa_yTaDHJLlQr7oX8Lp1kswHAJ3xXR15AI1ekvuzWV6Uc1XUMXSKAU7E5ZtYz.2laOqvK4RSlMQSFe), jump to 53:40 mark) and had some questions / comments.

I think what you are after is "verify the verifier", right?  E.g. that the wallet knows who the verifier is via a VC before responding. 

If you are going to use AnonCreds for that, you do need to have a presentation request before the presentation. That is because the presentation request has required data necessary to construct the request -- at minimum a nonce to ensure replaying of a VC is not possible.

The Wallet could have a pre-defined list of "valid" verifiers by DID/identitifier, or could use a trust registry to look up the DID/identifier of the verifier before responding.

We are working on a concept called "<did>/whois" for this type of purpose -- a distributed Trust Registry concept. Given a published, resolvable DID, support (ideally, across all published DID Methods) the endpoint <did>/whois, which returns a W3C signed VP containing VCs about the DID and/or the entity behind the DID -- e.g. a VC issued by a "trusted" registry.  Given that, the Presentation Request from a unknown verifier could come in and the wallet could use the DID of Verifier to resolve `<did>/whois` to find out what is known about the verifier.  For details:

> We talked about this at yesterday's ID Working Group call, and it was suggested that I post this notice, get an feedback and we can have a formal request to start the work item at the next call.   Background material:
> * Recording from yesterday's call -- starts at the 28:00 minute mark of the recording: [https://us02web.zoom.us/rec/play/J-ls1Je-LMfnOpqTYg-y3iDLsHmM9qR_o9oNm5aSZjQhPeMLLWm[…]jOihLh7CZayKe3SfjSiCxw9b5lMKn87L-un7DPdDz2xi.B4VKBiapLbk0q45r](https://us02web.zoom.us/rec/play/J-ls1Je-LMfnOpqTYg-y3iDLsHmM9qR_o9oNm5aSZjQhPeMLLWmparzLhBolTO6ybBA33bwfpJ-7Tn37.Q_zX7She7XN9wuir?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fus02web.zoom.us%2Frec%2Fshare%2Fq5Inpjc7FX-l5akpVD2ujOihLh7CZayKe3SfjSiCxw9b5lMKn87L-un7DPdDz2xi.B4VKBiapLbk0q45r)
Presentation from the call: https://docs.google.com/presentation/d/1jC-KBr__k2CEaZtka2NYRzRwbw48ck4fXI5D4JBg_Sk/edit?usp=drive_link
> * Background of /whois in did:tdw specification: https://identity.foundation/trustdidweb/#the-whois-use-case
> * Mechanism for /whois in did:tdw specification: https://identity.foundation/trustdidweb/#whois-linkedvp-service
> * <did>/whois  is based on the DIF Linked-VP specification: https://identity.foundation/linked-vp/
> * <did>/whois is the very clever idea of 
[@John Jordan (Gov BC)](https://difdn.slack.com/team/U798Z89A4)

Hope that helps.

**Comment by ikamii** [comment]
Hi @swcurran,

Thank you for your detailed answer. 

I should maybe check out AnonCreds for now in my case, but I am going to watch the given zoom recording as well thank you for that.

Best,
